---

baseurl:     "/same_pinch_web" # the subpath of your site, e.g. /blog/
url:         "http://www.maisasolutions.com"


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, .idea]
permalink: pretty
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "MSocial"
keywords:    "SinglePaged, jekyll, template, github, blog, single page"
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/t413/SinglePaged"
favicon:     ""
touch_icon:  ""
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)

